// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfnm7y5MX3zeqGhTtFgEW5OAzbV7A0AAQ',
    appId: '1:1628079546:web:78fd7e04cb7c3bccd3c983',
    messagingSenderId: '1628079546',
    projectId: 'fuel-tracker-030311',
    authDomain: 'fuel-tracker-030311.firebaseapp.com',
    storageBucket: 'fuel-tracker-030311.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALpQeJXD1MBKVqlOX1j7Xn4Zynf2kQZ4M',
    appId: '1:1628079546:android:8d2487bd8e55e1c0d3c983',
    messagingSenderId: '1628079546',
    projectId: 'fuel-tracker-030311',
    storageBucket: 'fuel-tracker-030311.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBddzwy1cEXCytHsA4wpd_TRZJKsSluYLY',
    appId: '1:1628079546:ios:981cf70603d3a643d3c983',
    messagingSenderId: '1628079546',
    projectId: 'fuel-tracker-030311',
    storageBucket: 'fuel-tracker-030311.firebasestorage.app',
    iosBundleId: 'com.example.fuelTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfnm7y5MX3zeqGhTtFgEW5OAzbV7A0AAQ',
    appId: '1:1628079546:web:e2c1209784b9da1bd3c983',
    messagingSenderId: '1628079546',
    projectId: 'fuel-tracker-030311',
    authDomain: 'fuel-tracker-030311.firebaseapp.com',
    storageBucket: 'fuel-tracker-030311.firebasestorage.app',
  );
}
